dependencies:
  build:
    - go:1.12.1

build_targets:
  - name: default
    tags:
      os: darwin

    commands:
      - go get
      - go build
      - go test ./...

ci:
  builds:
    - name: default
      build_target: default
      when: branch is 'master'


package:
  docker:
    base_image: ubuntu
    image: demo-server
    working_dir: /
    exec: /demo-server
  artifacts:
    - demo-server
