dependencies:
  build:
    - go:1.12.1

build_targets:
  - name: default
    dependencies:
      containers:
        redis:
          label: redis
          image: redis:latest
    tags:
      os: linux
      project: 1

    commands:
      - go get
      - go build
      - go test ./...

  - name: deploy
    tags:
      os: linux

    commands:
      - go get
      - go build
      - go test ./...
      # yb package ...
ci:
  builds:
    - name: default
      build_target: default
      when: branch is 'master' OR action is 'pull_request'


package:
  docker:
    base_image: alpine
    image: demo-server
    working_dir: /
    exec: /demo-server
  artifacts:
    - demo-server
