dependencies:
  build:
    - go:1.15.4

build_targets:
  - name: default
    environment:
      - SKIPPER_IGNORE=ls
    commands:
      - ls
      - ls -alt
      - go get
      - go build
      - go test ./...

  - name: sleep
    environment:
      - SKIPPER_IGNORE=ls
    commands:
      - ls
      - ls -alt
      - echo 'about to sleep'
      - sleep 150
      - echo 'sleep over'
      - go get
      - go build
      - go test ./...

  - name: mac
    environment:
      - SKIPPER_IGNORE=ls
    commands:
      - ls
      - go get
      - go build
      - go test ./...

  - name: deploy
    tags:
      os: linux
    commands:
      - go get
      - go build
      - go test ./...
      # yb package ...
ci:
  builds:
    - name: default
      build_target: default
      when: branch is 'master' OR action is 'pull_request'
