dependencies:
  build:
    - go:1.14.1

build_targets:
  - name: default
    tags:
      os: linux
    environment:
      - SKIPPER_IGNORE="ls"
    commands:
      - ls
      - go get
      - go build
      - go test ./...

  - name: mac
    tags:
      os: linux

    commands:
      - ls
      - go get
      - go build
      - go test ./...

  - name: deploy
    tags:
      os: linux

    commands:
      - go get
      - go build
      - go test ./...
      # yb package ...
ci:
  builds:
    - name: default
      build_target: default
      when: branch is 'master' OR action is 'pull_request'


package:
  docker:
    base_image: alpine
    image: demo-server
    working_dir: /
    exec: /demo-server
  artifacts:
    - demo-server
