dependencies:
  build:
    - go:1.15.4

build_targets:
  - name: default
    tags:
      os: linux
    container:
      image: yourbase/yb_ubuntu:18.04-nonroot
    environment:
      - SKIPPER_IGNORE=ls
    commands:
      - ls
      - env
      - go get
      - go build
      - go test ./...

  - name: mac
    environment:
      - SKIPPER_IGNORE=ls
    commands:
      - ls
      - env
      - go get
      - go build
      - go test ./...

  - name: deploy
    tags:
      os: linux
    commands:
      - go get
      - go build
      - go test ./...
      # yb package ...
ci:
  builds:
    - name: default
      build_target: default
      when: branch is 'master' OR action is 'pull_request'

